version: '2'
volumes:
  gitlab-data:
    driver: rancher-nfs
    per_container: false
services:
  gitlab-server-rancher-nfs:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.vidomia.biz
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.vidomia.biz'
    volumes:
    - gitlab-data: /etc/gitlab
    - gitlab-data: /var/log/gitlab
    - gitlab-data: /var/opt/gitlab
    ports:
    - 22:22/tcp
    - 80:80/tcp
    - 443:443/tcp