version: '2'
services:
  gitlab-server-rancher-nfs:
    retain_ip: true
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 80
      unhealthy_threshold: 3
      interval: 30000
      strategy: recreate