version: '2'
services:
  redis-vidomia-nfs-master:
    retain_ip: true
    scale: 1
    start_on_create: true
  redis-vidomia-nfs-slave:
    retain-ip: false
    scale: 3
    start_on_create: true